### ISSUE TITLE
NPE when creating a new world

### ISSUE THREAD

**Issue by tliron** [bergerhealer/MyWorlds#28]
Here is the error log:
```
Jul 05 00:27:23 SERVER  java[3297734]: [00:27:23] [Server thread/ERROR]: Unhandled exception executing command 'world' in plugin My_Worlds v1.19-v1
Jul 05 00:27:23 SERVER  java[3297734]: java.lang.NullPointerException: Cannot invoke "com.bergerkiller.bukkit.mw.MyWorlds.getLogger()" because "com.bergerkiller.bukkit.mw.MyWorlds.plugin" is null
Jul 05 00:27:23 SERVER  java[3297734]:         at com.bergerkiller.bukkit.mw.WorldManager.createWorld(WorldManager.java:392) ~[?:?]
Jul 05 00:27:23 SERVER  java[3297734]:         at com.bergerkiller.bukkit.mw.commands.WorldCreate.execute(WorldCreate.java:76) ~[?:?]
Jul 05 00:27:23 SERVER  java[3297734]:         at com.bergerkiller.bukkit.mw.commands.registry.MyWorldsCommands.execute(MyWorldsCommands.java:44) ~[?:?]
Jul 05 00:27:23 SERVER  java[3297734]:         at com.bergerkiller.bukkit.mw.MyWorlds.command(MyWorlds.java:356) ~[?:?]
Jul 05 00:27:23 SERVER  java[3297734]:         at com.bergerkiller.bukkit.common.PluginBase.onCommand(PluginBase.java:1265) ~[?:?]
Jul 05 00:27:23 SERVER  java[3297734]:         at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
Jul 05 00:27:23 SERVER  java[3297734]:         at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:149) ~[spigot-api-1.19-R0.1-SNAPSHOT.jar:?]
Jul 05 00:27:23 SERVER  java[3297734]:         at org.bukkit.craftbukkit.v1_19_R1.CraftServer.dispatchCommand(CraftServer.java:831) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.server.network.PlayerConnection.handleCommand(PlayerConnection.java:2031) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.server.network.PlayerConnection.a(PlayerConnection.java:1834) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.a(SourceFile:37) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.network.protocol.game.ServerboundChatCommandPacket.a(SourceFile:13) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.network.protocol.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:31) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.server.TickTask.run(SourceFile:18) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.util.thread.IAsyncTaskHandler.d(SourceFile:157) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.util.thread.IAsyncTaskHandlerReentrant.d(SourceFile:23) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:1150) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:1) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.util.thread.IAsyncTaskHandler.x(SourceFile:131) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.server.MinecraftServer.bh(MinecraftServer.java:1129) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.server.MinecraftServer.x(MinecraftServer.java:1122) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.util.thread.IAsyncTaskHandler.bq(SourceFile:116) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1105) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1014) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:291) ~[spigot-1.19-R0.1-SNAPSHOT.jar:3544-Spigot-475f600-991aeda]
Jul 05 00:27:23 SERVER  java[3297734]:         at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by bergerkiller** [comment]
Can you send the full server log using a pastebin service? Theres probably some error at startup.

**Comment by tliron** [comment]
Thanks for the quick response! I think the issue was that my server was overloaded. I increased the Bukkit timeout by a *lot* and it worked this time. :)

Are there recommended Bukkit and/or Java settings for this mod?

**Comment by bergerkiller** [comment]
Not really, MyWorlds doesnt really use a lot of memory. If you plan to create a lot of worlds, its a good idea to disable their spawn from being kept in memory, as that could use more memory than you may have.

**Comment by tliron** [comment]
Thanks!
