### ISSUE TITLE
BKCommonLib cannot save to file My_World\worlds.yml

### ISSUE THREAD

**Issue by Roos-Skywalker** [bergerhealer/MyWorlds#29]
Error triggers on server start. Is it because I am on 1.18.2?

[02:08:05] [Server thread/INFO]: [BKCommonLib] Enabling BKCommonLib v1.19.2-v1
[02:08:05] [Server thread/INFO]: [BKCommonLib] BKCommonLib is running on Purpur (Paper) (Spigot) (git-Purpur-1632) : v1_18_R2 (Minecraft 1.18.2)
[02:08:28] [BKCommonLib-IOWorker/ERROR]: [BKCommonLib.Configuration] An error occured while saving to file 'plugins\My_Worlds\worlds.yml':
java.nio.file.AccessDeniedException: C:\Users\RoosSkywalker.DESKTOP-2NI4VDK\Desktop\Mineculum\plugins\My_Worlds\worlds.yml.1659917308518.tmp -> plugins\My_Worlds\worlds.yml
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:89) ~[?:?]
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:103) ~[?:?]
	at sun.nio.fs.WindowsFileCopy.move(WindowsFileCopy.java:317) ~[?:?]
	at sun.nio.fs.WindowsFileSystemProvider.move(WindowsFileSystemProvider.java:293) ~[?:?]
	at java.nio.file.Files.move(Files.java:1432) ~[?:?]
	at com.bergerkiller.bukkit.common.utils.StreamUtil.atomicReplace(StreamUtil.java:302) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.bukkit.common.io.AsyncTextWriter$1.move(AsyncTextWriter.java:71) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.bukkit.common.io.AsyncTextWriter$1.apply(AsyncTextWriter.java:65) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at com.bergerkiller.bukkit.common.io.AsyncTextWriter$1.apply(AsyncTextWriter.java:55) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510) ~[?:?]
	at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147) ~[?:?]
	at com.bergerkiller.bukkit.common.utils.CommonUtil.lambda$runCheckedAsync$3(CommonUtil.java:695) ~[BKCommonLib-1.19.2-v1-1352.jar:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by bergerkiller** [comment]
Don't think so, first time I've seen this one. Its unable to overwrite the old configuration file with the new data. If you copied the previous configuration from a backup, perhaps the access rights are wrong?

Dunno how that works on windows, its all administrator rights on my system lol

**Comment by bergerkiller** [comment]
Do you have worlds.yml open in a text editor?

**Comment by Roos-Skywalker** [comment]
No idea, I just restarted the server and the error is gone. Thank you for your quick response!
