### ISSUE TITLE
Failed to load player data for player

### ISSUE THREAD

**Issue by NoughtMatt** [bergerhealer/MyWorlds#65]
Hello!

I recently updated my server from Paper 1.20.4 to 1.20.6, and every now and then, the console logs `[My_Worlds] Failed to load player data for <player>`. From the stack trace, it looks like it's related to teleporting between worlds, but it doesn't happen every time a player teleports, only occasionally.

I updated the following:
- Paper 1.20.4-496 to Paper 1.20.6-137
- BKCommonLib 1.20.4-v4-1691 to BKCommonLib 1.20.6-v1-SNAPSHOT-1745
- MyWorlds 1.20.4-v4-SNAPSHOT-280.jar to MyWorlds-1.20.6-v1-SNAPSHOT-290

<details>
<summary>Stack trace</summary>

```java
java.lang.IllegalArgumentException: BODY is not valid for players!
	at org.bukkit.craftbukkit.inventory.CraftInventoryPlayer.getItem(CraftInventoryPlayer.java:171) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at com.bergerkiller.mountiplex.reflection.util.fast.GeneratedInvoker$mpldefgen39a23f73.invoke(Unknown Source) ~[?:?]
	at BKCommonLib-1.20.6-v1-SNAPSHOT-1745.jar/com.bergerkiller.mountiplex.reflection.declarations.Template$Method.invoke(Template.java:1548) ~[BKCommonLib-1.20.6-v1-SNAPSHOT-1745.jar:?]
	at BKCommonLib-1.20.6-v1-SNAPSHOT-1745.jar/com.bergerkiller.bukkit.common.utils.EntityUtil.getEquipment(EntityUtil.java:192) ~[BKCommonLib-1.20.6-v1-SNAPSHOT-1745.jar:?]
	at MyWorlds-1.20.6-v1-SNAPSHOT-290.jar/com.bergerkiller.bukkit.mw.Util.getEquipmentBKCL(Util.java:327) ~[MyWorlds-1.20.6-v1-SNAPSHOT-290.jar:?]
	at MyWorlds-1.20.6-v1-SNAPSHOT-290.jar/com.bergerkiller.bukkit.mw.Util.getEquipment(Util.java:312) ~[MyWorlds-1.20.6-v1-SNAPSHOT-290.jar:?]
	at MyWorlds-1.20.6-v1-SNAPSHOT-290.jar/com.bergerkiller.bukkit.mw.MWPlayerDataController.refreshState(MWPlayerDataController.java:686) ~[MyWorlds-1.20.6-v1-SNAPSHOT-290.jar:?]
	at MyWorlds-1.20.6-v1-SNAPSHOT-290.jar/com.bergerkiller.bukkit.mw.WorldConfig.onPlayerEnter(WorldConfig.java:724) ~[MyWorlds-1.20.6-v1-SNAPSHOT-290.jar:?]
	at MyWorlds-1.20.6-v1-SNAPSHOT-290.jar/com.bergerkiller.bukkit.mw.MWListener.onPlayerChangedWorld(MWListener.java:459) ~[MyWorlds-1.20.6-v1-SNAPSHOT-290.jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor115.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:81) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:1.20.6-137-bd5867a]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:627) ~[paper-api-1.20.6-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:986) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.players.PlayerList.respawn(PlayerList.java:816) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1489) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.craftbukkit.entity.CraftPlayer.teleport(CraftPlayer.java:1348) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at MyWorlds-1.20.6-v1-SNAPSHOT-290.jar/com.bergerkiller.bukkit.mw.portal.PortalTeleportationHandler.performTeleportation(PortalTeleportationHandler.java:179) ~[MyWorlds-1.20.6-v1-SNAPSHOT-290.jar:?]
	at MyWorlds-1.20.6-v1-SNAPSHOT-290.jar/com.bergerkiller.bukkit.mw.portal.PortalTeleportationHandler.lambda$scheduleTeleportationWithVelocity$1(PortalTeleportationHandler.java:162) ~[MyWorlds-1.20.6-v1-SNAPSHOT-290.jar:?]
	at BKCommonLib-1.20.6-v1-SNAPSHOT-1745.jar/com.bergerkiller.bukkit.common.internal.CommonNextTickExecutor$ExecutorTask.run(CommonNextTickExecutor.java:161) ~[BKCommonLib-1.20.6-v1-SNAPSHOT-1745.jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:482) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1699) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:467) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1571) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1231) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[paper-1.20.6.jar:1.20.6-137-bd5867a]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
```
</details>

Thank you for your time!

**Comment by bergerkiller** [comment]
Looks like bukkit added an equipment slot:

```
    /**
     * Only for certain entities such as horses and wolves.
     */
    BODY(() -> EquipmentSlotGroup.ARMOR);
```

And instead of just returning null for 'invalid' slots, it throws an error. Kinda bad design on bukkits part but oh well.
Ill add a filter for BODY to avoid this problem.

**Comment by bergerkiller** [comment]
Updating either and/or both should fix the issue.

https://ci.mg-dev.eu/job/BKCommonLib/1747/
https://ci.mg-dev.eu/job/MyWorlds/291/

**Comment by NoughtMatt** [comment]
Thanks for the quick turnaround!

After a few minutes of randomly teleporting between worlds, it looks like the issue is gone. I'll keep monitoring the server for a bit when people join and roam around a bunch.

Thanks again!
