### ISSUE TITLE
Clash with the Mythic Dungeon plugin

### ISSUE THREAD

**Issue by qnsqns** [bergerhealer/MyWorlds#74]
[15:59:16 ERROR]: [My_Worlds] Failed to check whether world is a mythic dungeons world
java.lang.NoClassDefFoundError: net/playavalon/mythicdungeons/dungeons/Instance
        at com.bergerkiller.bukkit.mw.mythicdungeons.MythicDungeonsHelper$1.getSameDungeonWorlds(MythicDungeonsHelper.java:57) ~[MyWorlds-1.20.6-v1-294.jar:?]
        at com.bergerkiller.bukkit.mw.WorldConfig.detectMythicDungeonsInstance(WorldConfig.java:165) ~[MyWorlds-1.20.6-v1-294.jar:?]
        at com.bergerkiller.bukkit.mw.WorldConfig.onWorldLoad(WorldConfig.java:743) ~[MyWorlds-1.20.6-v1-294.jar:?]
        at com.bergerkiller.bukkit.mw.MWListener.onWorldLoad(MWListener.java:123) ~[MyWorlds-1.20.6-v1-294.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor161.execute(Unknown Source) ~[?:?]        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-2062]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.createWorld(CraftServer.java:1378) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.Bukkit.createWorld(Bukkit.java:804) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.WorldCreator.createWorld(WorldCreator.java:474) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.playavalon.mythicdungeons.api.parents.instances.AbstractInstance.lambda$initMap$1(AbstractInstance.java:193) ~[MythicDungeons-2.0.0-SNAPSHOT.jar:?]
        at net.playavalon.mythicdungeons.utility.tasks.ProcessTimer.run(ProcessTimer.java:12) ~[MythicDungeons-2.0.0-SNAPSHOT.jar:?]
        at net.playavalon.mythicdungeons.api.parents.instances.AbstractInstance.initMap(AbstractInstance.java:192) ~[MythicDungeons-2.0.0-SNAPSHOT.jar:?]
        at net.playavalon.mythicdungeons.api.parents.instances.AbstractInstance.initMap(AbstractInstance.java:155) ~[MythicDungeons-2.0.0-SNAPSHOT.jar:?]
        at net.playavalon.mythicdungeons.api.parents.instances.AbstractInstance.lambda$init$0(AbstractInstance.java:103) ~[MythicDungeons-2.0.0-SNAPSHOT.jar:?]

**Comment by bergerkiller** [comment]
try with https://ci.mg-dev.eu/job/MyWorlds/309/ I added support for the premium 2.0.0 build yesterday
