### ISSUE TITLE
error Players cannot enter the dungeon

### ISSUE THREAD

**Issue by qnsqns** [bergerhealer/MyWorlds#75]
[22:43:09 WARN]: [MythicDungeons] Task #54817 for MythicDungeons v2.0.0-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: 'java.util.concurrent.CompletableFuture org.bukkit.entity.Entity.teleportAsync(org.bukkit.Location, org.bukkit.event.player.PlayerTeleportEvent$TeleportCause, io.papermc.paper.entity.TeleportFlag[])'
        at net.playavalon.mythicdungeons.utility.helpers.Util.forceTeleport(Util.java:819) ~[MythicDungeons-2.0.0-SNAPSHOT (1).jar:?]
        at net.playavalon.mythicdungeons.api.parents.instances.InstancePlayable.addPlayer(InstancePlayable.java:275) ~[MythicDungeons-2.0.0-SNAPSHOT (1).jar:?]
        at net.playavalon.mythicdungeons.dungeons.dungeontypes.DungeonClassic.lambda$prepInstance$0(DungeonClassic.java:101) ~[MythicDungeons-2.0.0-SNAPSHOT (1).jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1506) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
[22:43:09 WARN]: [MythicDungeons] Task #54816 for MythicDungeons v2.0.0-SNAPSHOT generated an exception
java.lang.NoSuchMethodError: 'java.util.concurrent.CompletableFuture org.bukkit.entity.Entity.teleportAsync(org.bukkit.Location, org.bukkit.event.player.PlayerTeleportEvent$TeleportCause, io.papermc.paper.entity.TeleportFlag[])'
        at net.playavalon.mythicdungeons.utility.helpers.Util.forceTeleport(Util.java:819) ~[MythicDungeons-2.0.0-SNAPSHOT (1).jar:?]
        at net.playavalon.mythicdungeons.api.parents.instances.InstancePlayable.startGame(InstancePlayable.java:127) ~[MythicDungeons-2.0.0-SNAPSHOT (1).jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:480) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1506) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1420) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1191) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by bergerkiller** [comment]
Try opening this issue with mythic dungeons, I don't see how MyWorlds is related or can fix this, as its code in mythicdungeons thats failing (forceTeleport)
