### ISSUE TITLE
Not compatible with the development version of MythicDungeons!

### ISSUE THREAD

**Issue by starskymao** [bergerhealer/MyWorlds#76]
[ERROR]: [My_Worlds] Failed to identify mythic dungeons instance name field. Might be buggy!
java.lang.NoClassDefFoundError: net/playavalon/mythicdungeons/dungeons/Instance
        at com.bergerkiller.bukkit.mw.mythicdungeons.MythicDungeonsHelper.lambda$init$1(MythicDungeonsHelper.java:43) ~[MyWorlds-1.20.6-v1-294.jar:?]
        at com.bergerkiller.bukkit.common.utils.LogicUtil.tryCreate(LogicUtil.java:331) ~[BKCommonLib-1.20.6-v1-1749.jar:?]
        at com.bergerkiller.bukkit.mw.mythicdungeons.MythicDungeonsHelper.init(MythicDungeonsHelper.java:42) ~[MyWorlds-1.20.6-v1-294.jar:?]
        at com.bergerkiller.bukkit.mw.MyWorlds$1.initialize(MyWorlds.java:116) ~[MyWorlds-1.20.6-v1-294.jar:?]
        at com.bergerkiller.bukkit.mw.MyWorlds$1.initialize(MyWorlds.java:103) ~[MyWorlds-1.20.6-v1-294.jar:?]
        at com.bergerkiller.bukkit.common.softdependency.SoftDependency.handleEnable(SoftDependency.java:320) ~[BKCommonLib-1.20.6-v1-1749.jar:?]
        at com.bergerkiller.bukkit.common.softdependency.SoftDependency.detect(SoftDependency.java:234) ~[BKCommonLib-1.20.6-v1-1749.jar:?]
        at com.bergerkiller.bukkit.common.softdependency.SoftDetectableDependency.detectAll(SoftDetectableDependency.java:40) ~[BKCommonLib-1.20.6-v1-1749.jar:?]
        at com.bergerkiller.bukkit.common.softdependency.SoftDependency.detectAll(SoftDependency.java:184) ~[BKCommonLib-1.20.6-v1-1749.jar:?]
        at com.bergerkiller.bukkit.mw.MyWorlds.enable(MyWorlds.java:389) ~[MyWorlds-1.20.6-v1-294.jar:?]
        at com.bergerkiller.bukkit.common.PluginBase.onEnable(PluginBase.java:861) ~[BKCommonLib-1.20.6-v1-1749.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:506) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:660) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:571) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:622) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:421) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1106) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.playavalon.mythicdungeons.dungeons.Instance
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
        ... 23 more
[INFO]: [My_Worlds] Mythic Dungeons detected: dungeon instances will automatically share inventory settings
[INFO]: [PlaceholderAPI] Successfully registered internal expansion: myworlds [1.20.6-v1]
[INFO]: [PlaceholderAPI] Successfully registered internal expansion: mw [1.20.6-v1]
[INFO]: [My_Worlds] PlaceholderAPI integration enabled
[INFO]: [My_Worlds] My_Worlds version 1.20.6-v1 (build: 294) enabled! (0.338s)
[ERROR]: [My_Worlds] Failed to identify mythic dungeons instance name field. Might be buggy!
java.lang.NoClassDefFoundError: net/playavalon/mythicdungeons/dungeons/Instance
        at com.bergerkiller.bukkit.mw.mythicdungeons.MythicDungeonsHelper.lambda$init$1(MythicDungeonsHelper.java:43) ~[MyWorlds-1.20.6-v1-294.jar:?]
        at com.bergerkiller.bukkit.common.utils.LogicUtil.tryCreate(LogicUtil.java:331) ~[BKCommonLib-1.20.6-v1-1749.jar:?]
        at com.bergerkiller.bukkit.mw.mythicdungeons.MythicDungeonsHelper.init(MythicDungeonsHelper.java:42) ~[MyWorlds-1.20.6-v1-294.jar:?]
        at com.bergerkiller.bukkit.mw.MyWorlds$1.initialize(MyWorlds.java:116) ~[MyWorlds-1.20.6-v1-294.jar:?]
        at com.bergerkiller.bukkit.mw.MyWorlds$1.initialize(MyWorlds.java:103) ~[MyWorlds-1.20.6-v1-294.jar:?]
        at com.bergerkiller.bukkit.common.softdependency.SoftDependency.handleEnable(SoftDependency.java:320) ~[BKCommonLib-1.20.6-v1-1749.jar:?]
        at com.bergerkiller.bukkit.common.softdependency.SoftDependency.detect(SoftDependency.java:234) ~[BKCommonLib-1.20.6-v1-1749.jar:?]
        at com.bergerkiller.bukkit.common.softdependency.SoftDependency$EnableEntry.run(SoftDependency.java:672) ~[BKCommonLib-1.20.6-v1-1749.jar:?]
        at com.bergerkiller.bukkit.common.softdependency.SoftDependency$AfterPluginEnableHook.bake(SoftDependency.java:655) ~[BKCommonLib-1.20.6-v1-1749.jar:?]
        at org.bukkit.event.HandlerList.bakeAll(HandlerList.java:51) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:206) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:506) ~[leaf-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:660) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:571) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:622) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:421) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:353) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1106) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[leaf-1.20.1.jar:git-Leaf-"c6ef60f"]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: net.playavalon.mythicdungeons.dungeons.Instance
        ... 21 more
[INFO]: [My_Worlds] Mythic Dungeons detected: dungeon instances will automatically share inventory settings

**Comment by bergerkiller** [comment]
Update myworlds AND bkcommonlib to the new 1.21.1 release to add support for mythic dungeons 2.0.0. It works on the 1.20.1 version of the server.
